name: Build and Update Production Branch

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project files
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installing Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build Project
        run: yarn run build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact_dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main-production_ready"
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_dist
          path: dist
      - name: Push to production branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull origin main-production_ready
          git add dist
          git commit -m "chore(release): update production assets [v${{ github.ref_name}}] [build-${{ github.run_id }}]"
          git push
      - name: Tag Release
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
